version: "3.9"

# Common template for CKAN services below
x-common-ckan:
  &default-common-ckan
  restart: on-failure
  env_file:
    - .env

services:
  redis:
    << : *default-common-ckan
    container_name: redis-${COMPOSE_PROFILES}
    image: "redis:alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5

  db:
    << : *default-common-ckan
    build:
      context: ./docker/db/
    image: dcatapit_postgis-${COMPOSE_PROFILES}:latest
    container_name: db-${COMPOSE_PROFILES}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  ckan:
    << : *default-common-ckan
    build:
      context: ./docker/ckan/
    container_name: ckan-${COMPOSE_PROFILES}
    image: dcatapit_ckan-${COMPOSE_PROFILES}:latest
    cap_add:
      - SYS_PTRACE
    depends_on:
      solr:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${CKAN_PORT}:5000"
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-config:/etc/ckan
      - ckan-logs:/var/log/ckan
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 10s
      # this is quite high to avoid the check failing because ckan is not yet configured.
      retries: 30

  datapusher:
    << : *default-common-ckan
    container_name: datapusher-${COMPOSE_PROFILES}
    image: keitaro/ckan-datapusher:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 10s
      retries: 5

  solr:
    << : *default-common-ckan
    build:
      context: ./docker/solr/
    container_name: solr-${COMPOSE_PROFILES}
    image: dcatapit_solr-${COMPOSE_PROFILES}:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8983"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - solr-data:/opt/solr/server/solr/ckan/data

  gather_consumer:
    << : *default-common-ckan
    depends_on:
      ckan:
        condition: service_healthy
    container_name: gather-${COMPOSE_PROFILES}
    entrypoint: /consumer-entrypoint.sh
    image: dcatapit_ckan-${COMPOSE_PROFILES}:latest
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-config:/etc/ckan
      - ckan-logs:/var/log/ckan
      - ./docker/ckan/ckan_harvesting_gather.conf:/etc/supervisor/conf.d/ckan_harvesting.conf

  fetch_consumer:
    << : *default-common-ckan
    depends_on:
      ckan:
        condition: service_healthy
    container_name: fetch-${COMPOSE_PROFILES}
    entrypoint: /consumer-entrypoint.sh
    image: dcatapit_ckan-${COMPOSE_PROFILES}:latest
    volumes:
      - ckan-data:/var/lib/ckan
      - ckan-config:/etc/ckan
      - ckan-logs:/var/log/ckan
      - ./docker/ckan/ckan_harvesting_fetch.conf:/etc/supervisor/conf.d/ckan_harvesting.conf

  # proxy:
  #   << : *default-common-ckan
  #   image: ghcr.io/linuxserver/swag:latest
  #   container_name: proxy
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - proxy-config:/config
  #     - ./site-confs/default:/config/nginx/site-confs/default
  #   ports:
  #     - "443:443"
  #     - "80:80" #optional
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:80"]
  #     interval: 10s
  #     timeout: 10s
  #     retries: 5

volumes:
  proxy-config:
  ckan-data:
  ckan-config:
  ckan-logs:
  solr-data:
  db:
